In [1]:
import pandas as pd
import numpy as  np
# creating a random dataset
study_hours = np.random.normal(10,2,1000)
sleeping_hours = np.random.normal(10,2,1000)
passed = (study_hours+np.random.normal(0,1,1000))>(sleeping_hours + np.random.normal(0,1,1000))
passed = passed.astype(int)


In [2]:
df = pd.DataFrame({'study_hours': study_hours,"sleeping_hours": sleeping_hours,"passed":passed})
df['passed'].value_counts()

passed
1    515
0    485
Name: count, dtype: int64

In [3]:
df

study_hours  sleeping_hours  passed
0       8.552710        9.604159       0
1      11.895592       10.723583       1
2       7.285055        7.944051       0
3       6.503999        7.698652       1
4      11.283593        9.111547       1
..           ...             ...     ...
995    13.042680       11.150794       1
996     9.398485        6.718868       1
997     9.801908       10.434486       0
998     9.059105       13.445346       0
999    12.052540        8.998361       1

[1000 rows x 3 columns]

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [5]:
x = df[['study_hours','sleeping_hours']]
y = df['passed']
x_train, x_test, y_train, y_test, = train_test_split(x,y,test_size= 0.2, random_state=20)

In [6]:
log_model = LogisticRegression()
log_model.fit(x_train,y_train)

LogisticRegression()

In [7]:
y_pred = log_model.predict(x_test)

In [8]:
y_pred

array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1])

accuracy = total correct prediction/
precion  = tp\tp+fp
recall_score =  tp\tp+fn

# confusion_matrix

In [9]:
from sklearn.metrics import confusion_matrix #tp+tn\fp+tp+fn+tn
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score  #tp\tp+fp
from sklearn.metrics import recall_score # tp\+tp+fn
from sklearn.metrics import classification_report

In [10]:
print("confusion matrix") 
print(confusion_matrix(y_test,y_pred))                #tp+tn\fp+tp+fn+tn
print("Accuracy :- ",accuracy_score(y_test,y_pred))
print("Precision :- ",precision_score(y_test,y_pred)) #tp\tp+fp
print("Recall :- ",recall_score(y_test,y_pred)) # tp\+tp+fn
print(classification_report(y_test,y_pred))

confusion matrix
[[78 13]
 [15 94]]
Accuracy :-  0.86
Precision :-  0.8785046728971962
Recall :-  0.8623853211009175
              precision    recall  f1-score   support

           0       0.84      0.86      0.85        91
           1       0.88      0.86      0.87       109

    accuracy                           0.86       200
   macro avg       0.86      0.86      0.86       200
weighted avg       0.86      0.86      0.86       200



In [11]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85        91
           1       0.88      0.86      0.87       109

    accuracy                           0.86       200
   macro avg       0.86      0.86      0.86       200
weighted avg       0.86      0.86      0.86       200



# SVM (support vector machine)

In [17]:
from sklearn import datasets
import pandas as pd 
                     # Importing iris data ( as a data set which is provied of data)


iris = datasets.load_iris()   #ris dataset is the Hello World for the Data Science,
                            #so if you have started your career in Data Science and Machine Learning
                            #  you will be practicing basic ML algorithms on this famous dataset.
                            #  Iris dataset contains five columns such as Petal Length, Petal Width,
                            #  Sepal Length, Sepal Width and Species Type.

In [18]:
df = pd.DataFrame(data =iris.data, columns = iris.feature_names ) # as function which is used for 
df["species"] = iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                  5.1               3.5                1.4               0.2  \
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [19]:
x = df.drop(['species'], axis = 1) # ek pariticular data ko lene ke liiye

y = df['species']

x_train, x_test, y_train, y_test, = train_test_split(x,y,test_size= 0.1, random_state=50)

In [20]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [21]:
print("confusion matrix")
print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

confusion matrix
[[6 0 0]
 [0 4 0]
 [0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         5

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

